### ISSUE TITLE
Problem running the App

### ISSUE THREAD

**Issue by kaleb-dev** [lMelkorl/Space-Game#1]
Hi there, I'm having trouble opening up the app in the terminal. If so can you show me how to access this game on the terminal? I keep getting the error:

npm ERR! syscall open
npm ERR! path C:\Users\sisad\Downloads\Space-Game-master/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\sisad\Downloads\Space-Game-master\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by lMelkorl** [comment]
hi, make sure you have full access to the file directory also I suggest you have a look at this thread 

https://stackoverflow.com/questions/49415958/what-could-cause-an-error-related-to-npm-not-being-able-to-find-a-file-no-conte
